In [1]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [1]:
#Installing Python package for stacking
!pip install vecstack

In [2]:
#Importing necessary libraties and metrics
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import classification_report, confusion_matrix
#Importing necessary classifier packages-Base-level learners
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
#Importing necessary classifier package-High-level learners
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
#For One-Hot_Encoding
from sklearn.preprocessing import OneHotEncoder
#for stacking
from vecstack import stacking
#Warnings
import warnings
warnings.filterwarnings("ignore")

In [3]:
#Importing train and test data
TrainFile = r'C:\Users\Arun Iyer\OneDrive\Desktop\ASU Q1\Data Mining 1\Team Assignment 1\Restraunt revenue Training and test data\train.csv'
Train_Data = pd.read_csv(TrainFile)
TestFile = r'C:\Users\Arun Iyer\OneDrive\Desktop\ASU Q1\Data Mining 1\Team Assignment 1\Restraunt revenue Training and test data\test.csv'
Test_Data = pd.read_csv(TestFile)
Train_Data

Id   Open Date        City  City Group Type  P1   P2   P3   P4  P5  ...  \
0      0  07/17/1999    İstanbul  Big Cities   IL   4  5.0  4.0  4.0   2  ...   
1      1  02/14/2008      Ankara  Big Cities   FC   4  5.0  4.0  4.0   1  ...   
2      2  03/09/2013  Diyarbakır       Other   IL   2  4.0  2.0  5.0   2  ...   
3      3  02/02/2012       Tokat       Other   IL   6  4.5  6.0  6.0   4  ...   
4      4  05/09/2009   Gaziantep       Other   IL   3  4.0  3.0  4.0   2  ...   
..   ...         ...         ...         ...  ...  ..  ...  ...  ...  ..  ...   
132  132  06/25/2008     Trabzon       Other   FC   2  3.0  3.0  5.0   4  ...   
133  133  10/12/2006       İzmir  Big Cities   FC   4  5.0  4.0  4.0   2  ...   
134  134  07/08/2006     Kayseri       Other   FC   3  4.0  4.0  4.0   2  ...   
135  135  10/29/2010    İstanbul  Big Cities   FC   4  5.0  4.0  5.0   2  ...   
136  136  09/01/2009    İstanbul  Big Cities   FC   4  5.0  3.0  5.0   2  ...   

     P29  P30  P31  P32  P33  P34  P35  P36  P37    revenue  
0    3.0    5    3    4    5    5    4    3    4  5653753.0  
1    3.0    0    0    0    0    0    0    0    0  6923131.0  
2    3.0    0    0    0    0    0    0    0    0  2055379.0  
3    7.5   25   12   10    6   18   12   12    6  2675511.0  
4    3.0    5    1    3    2    3    4    3    3  4316715.0  
..   ...  ...  ...  ...  ...  ...  ...  ...  ...        ...  
132  3.0    0    0    0    0    0    0    0    0  5787594.0  
133  3.0    0    0    0    0    0    0    0    0  9262754.0  
134  3.0    0    0    0    0    0    0    0    0  2544857.0  
135  3.0    0    0    0    0    0    0    0    0  7217634.0  
136  3.0    0    0    0    0    0    0    0    0  6363241.0  

[137 rows x 43 columns]

In [4]:
Test_Data

Id   Open Date            City  City Group Type  P1   P2   P3   P4  \
0          0  01/22/2011           Niğde       Other   FC   1  4.0  4.0  4.0   
1          1  03/18/2011           Konya       Other   IL   3  4.0  4.0  4.0   
2          2  10/30/2013          Ankara  Big Cities   FC   3  4.0  4.0  4.0   
3          3  05/06/2013         Kocaeli       Other   IL   2  4.0  4.0  4.0   
4          4  07/31/2013  Afyonkarahisar       Other   FC   2  4.0  4.0  4.0   
...      ...         ...             ...         ...  ...  ..  ...  ...  ...   
99995  99995  01/05/2000         Antalya       Other   FC   5  5.0  4.0  4.0   
99996  99996  07/18/2011           Niğde       Other   IL   1  2.0  4.0  3.0   
99997  99997  12/29/2012        İstanbul  Big Cities   IL   4  5.0  4.0  4.0   
99998  99998  10/12/2013        İstanbul  Big Cities   FC  12  7.5  6.0  6.0   
99999  99999  10/05/2010        İstanbul  Big Cities   IL   2  5.0  4.0  4.0   

       P5  ...  P28  P29  P30  P31  P32  P33  P34  P35  P36  P37  
0       1  ...  2.0  3.0    0    0    0    0    0    0    0    0  
1       2  ...  1.0  3.0    0    0    0    0    0    0    0    0  
2       2  ...  2.0  3.0    0    0    0    0    0    0    0    0  
3       2  ...  2.0  3.0    0    4    0    0    0    0    0    0  
4       1  ...  5.0  3.0    0    0    0    0    0    0    0    0  
...    ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
99995   2  ...  2.0  3.0    0    0    0    0    0    0    0    0  
99996   1  ...  1.0  3.0    5    0    0    0    4    0    0    0  
99997   1  ...  4.0  1.0    5    5    3    2    4    4    4    2  
99998   4  ...  7.5  5.0    0    0    0    4    0    0    0    0  
99999   2  ...  5.0  3.0    0    2    0    2    2    4    2    0  

[100000 rows x 42 columns]

In [5]:
print(Train_Data.shape)
print(Test_Data.shape)

(137, 43)
(100000, 42)


In [6]:
#Checking for null values in train data
Train_Data.isna().any()

Id            False
Open Date     False
City          False
City Group    False
Type          False
P1            False
P2            False
P3            False
P4            False
P5            False
P6            False
P7            False
P8            False
P9            False
P10           False
P11           False
P12           False
P13           False
P14           False
P15           False
P16           False
P17           False
P18           False
P19           False
P20           False
P21           False
P22           False
P23           False
P24           False
P25           False
P26           False
P27           False
P28           False
P29           False
P30           False
P31           False
P32           False
P33           False
P34           False
P35           False
P36           False
P37           False
revenue       False
dtype: bool

In [7]:
#Checking for null values in test data
Test_Data.isna().any()

Id            False
Open Date     False
City          False
City Group    False
Type          False
P1            False
P2            False
P3            False
P4            False
P5            False
P6            False
P7            False
P8            False
P9            False
P10           False
P11           False
P12           False
P13           False
P14           False
P15           False
P16           False
P17           False
P18           False
P19           False
P20           False
P21           False
P22           False
P23           False
P24           False
P25           False
P26           False
P27           False
P28           False
P29           False
P30           False
P31           False
P32           False
P33           False
P34           False
P35           False
P36           False
P37           False
dtype: bool

In [8]:
Y_Train = Train_Data.iloc[:, -1]
X_Train = Train_Data.iloc[:, :-1]
X_Test = Test_Data.copy()



In [27]:
#Converting Open Date from Object to DateTime
X_Train['Open Date']=pd.to_datetime(X_Train['Open Date'])

X_Test['Open Date']=pd.to_datetime(X_Test['Open Date'])

# Not needed since we are dropping

Id  Open Date            City  City Group Type  P1   P2   P3   P4  \
0          0 2011-01-22           Niğde       Other   FC   1  4.0  4.0  4.0   
1          1 2011-03-18           Konya       Other   IL   3  4.0  4.0  4.0   
2          2 2013-10-30          Ankara  Big Cities   FC   3  4.0  4.0  4.0   
3          3 2013-05-06         Kocaeli       Other   IL   2  4.0  4.0  4.0   
4          4 2013-07-31  Afyonkarahisar       Other   FC   2  4.0  4.0  4.0   
...      ...        ...             ...         ...  ...  ..  ...  ...  ...   
99995  99995 2000-01-05         Antalya       Other   FC   5  5.0  4.0  4.0   
99996  99996 2011-07-18           Niğde       Other   IL   1  2.0  4.0  3.0   
99997  99997 2012-12-29        İstanbul  Big Cities   IL   4  5.0  4.0  4.0   
99998  99998 2013-10-12        İstanbul  Big Cities   FC  12  7.5  6.0  6.0   
99999  99999 2010-10-05        İstanbul  Big Cities   IL   2  5.0  4.0  4.0   

       P5  ...  P28  P29  P30  P31  P32  P33  P34  P35  P36  P37  
0       1  ...  2.0  3.0    0    0    0    0    0    0    0    0  
1       2  ...  1.0  3.0    0    0    0    0    0    0    0    0  
2       2  ...  2.0  3.0    0    0    0    0    0    0    0    0  
3       2  ...  2.0  3.0    0    4    0    0    0    0    0    0  
4       1  ...  5.0  3.0    0    0    0    0    0    0    0    0  
...    ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
99995   2  ...  2.0  3.0    0    0    0    0    0    0    0    0  
99996   1  ...  1.0  3.0    5    0    0    0    4    0    0    0  
99997   1  ...  4.0  1.0    5    5    3    2    4    4    4    2  
99998   4  ...  7.5  5.0    0    0    0    4    0    0    0    0  
99999   2  ...  5.0  3.0    0    2    0    2    2    4    2    0  

[100000 rows x 42 columns]

In [28]:
X_Train.shape

(137, 42)

In [29]:
#Do one-hot encoding of categorical variables

combined_Data = pd.concat([X_Train, X_Test], keys=[0,1])

categoricalFeatures = ["City",
"City Group",
"Type"]


#Combine Train and test for one Hot Encoding
#combined_Data = pd.concat([Train_Data,Test_Data], keys=[0,1])

#Do one Hot encoding for categorical features
#combined_Data["y"]=combined_Data["y"].map({"yes":1,"no":0})
combined_Data=pd.get_dummies(combined_Data,columns=categoricalFeatures)
#Updated_Test_Data = pd.get_dummies(Test_Data,columns=categoricalFeatures)
#print(combined_Data['Revenue'])

#Separate Train data and test data
#X_train = combined_Data.xs(0)
#X_test = combined_Data.xs(1)
#X_train.to_csv("/gdrive/My Drive/CS508/updated_train.csv", index = None)
#X_test.to_csv("/gdrive/My Drive/CS508/updated_test.csv", index = None)
#X_train.head()
#X_test.head()


In [30]:
combined_Data.shape

(100137, 108)

In [31]:
Updated_Train_Data=combined_Data.xs(0)
Updated_Test_Data=combined_Data.xs(1)

In [32]:
Updated_Train_Data

Id  Open Date  P1   P2   P3   P4  P5  P6  P7  P8  ...  City_Çorum  \
0      0 1999-07-17   4  5.0  4.0  4.0   2   2   5   4  ...           0   
1      1 2008-02-14   4  5.0  4.0  4.0   1   2   5   5  ...           0   
2      2 2013-03-09   2  4.0  2.0  5.0   2   3   5   5  ...           0   
3      3 2012-02-02   6  4.5  6.0  6.0   4   4  10   8  ...           0   
4      4 2009-05-09   3  4.0  3.0  4.0   2   2   5   5  ...           0   
..   ...        ...  ..  ...  ...  ...  ..  ..  ..  ..  ...         ...   
132  132 2008-06-25   2  3.0  3.0  5.0   4   2   4   4  ...           0   
133  133 2006-10-12   4  5.0  4.0  4.0   2   3   5   4  ...           0   
134  134 2006-07-08   3  4.0  4.0  4.0   2   3   5   5  ...           0   
135  135 2010-10-29   4  5.0  4.0  5.0   2   2   5   5  ...           0   
136  136 2009-09-01   4  5.0  3.0  5.0   2   2   5   4  ...           0   

     City_İstanbul  City_İzmir  City_Şanlıurfa  City Group_Big Cities  \
0                1           0               0                      1   
1                0           0               0                      1   
2                0           0               0                      0   
3                0           0               0                      0   
4                0           0               0                      0   
..             ...         ...             ...                    ...   
132              0           0               0                      0   
133              0           1               0                      1   
134              0           0               0                      0   
135              1           0               0                      1   
136              1           0               0                      1   

     City Group_Other  Type_DT  Type_FC  Type_IL  Type_MB  
0                   0        0        0        1        0  
1                   0        0        1        0        0  
2                   1        0        0        1        0  
3                   1        0        0        1        0  
4                   1        0        0        1        0  
..                ...      ...      ...      ...      ...  
132                 1        0        1        0        0  
133                 0        0        1        0        0  
134                 1        0        1        0        0  
135                 0        0        1        0        0  
136                 0        0        1        0        0  

[137 rows x 108 columns]

In [74]:
Updated_Test_Data

P1   P2   P3   P4  P5  P6  P7  P8  P9  P10  ...  City_Çorum  \
0       1  4.0  4.0  4.0   1   2   5   4   5    5  ...           0   
1       3  4.0  4.0  4.0   2   2   5   3   4    4  ...           0   
2       3  4.0  4.0  4.0   2   2   5   4   4    5  ...           0   
3       2  4.0  4.0  4.0   2   3   5   4   5    4  ...           0   
4       2  4.0  4.0  4.0   1   2   5   4   5    4  ...           0   
...    ..  ...  ...  ...  ..  ..  ..  ..  ..  ...  ...         ...   
99995   5  5.0  4.0  4.0   2   2   5   5   4    4  ...           0   
99996   1  2.0  4.0  3.0   1   1   1   5   5    5  ...           0   
99997   4  5.0  4.0  4.0   1   2   5   3   4    5  ...           0   
99998  12  7.5  6.0  6.0   4   4  10  10  10   10  ...           0   
99999   2  5.0  4.0  4.0   2   2   5   5   5    4  ...           0   

       City_İstanbul  City_İzmir  City_Şanlıurfa  City Group_Big Cities  \
0                  0           0               0                      0   
1                  0           0               0                      0   
2                  0           0               0                      1   
3                  0           0               0                      0   
4                  0           0               0                      0   
...              ...         ...             ...                    ...   
99995              0           0               0                      0   
99996              0           0               0                      0   
99997              1           0               0                      1   
99998              1           0               0                      1   
99999              1           0               0                      1   

       City Group_Other  Type_DT  Type_FC  Type_IL  Type_MB  
0                     1        0        1        0        0  
1                     1        0        0        1        0  
2                     0        0        1        0        0  
3                     1        0        0        1        0  
4                     1        0        1        0        0  
...                 ...      ...      ...      ...      ...  
99995                 1        0        1        0        0  
99996                 1        0        0        1        0  
99997                 0        0        0        1        0  
99998                 0        0        1        0        0  
99999                 0        0        0        1        0  

[100000 rows x 106 columns]

In [46]:
Updated_Train_Data.drop(labels="Open Date",axis=1,inplace=True)
Updated_Test_Data.drop(labels="Open Date",axis=1,inplace=True)

Updated_Train_Data.drop(labels="Id",axis=1,inplace=True)
Updated_Test_Data.drop(labels="Id",axis=1,inplace=True)

KeyError: "['Id'] not found in axis"

In [17]:
Updated_Train_Data.to_csv("/gdrive/My Drive/CS508/Updated_Train_Data.csv", index = None)
Updated_Test_Data.to_csv("/gdrive/My Drive/CS508/Updated_Test_Data.csv", index = None)

In [57]:
Updated_Test_Data

P1   P2   P3   P4  P5  P6  P7  P8  P9  P10  ...  City_Çorum  \
0       1  4.0  4.0  4.0   1   2   5   4   5    5  ...           0   
1       3  4.0  4.0  4.0   2   2   5   3   4    4  ...           0   
2       3  4.0  4.0  4.0   2   2   5   4   4    5  ...           0   
3       2  4.0  4.0  4.0   2   3   5   4   5    4  ...           0   
4       2  4.0  4.0  4.0   1   2   5   4   5    4  ...           0   
...    ..  ...  ...  ...  ..  ..  ..  ..  ..  ...  ...         ...   
99995   5  5.0  4.0  4.0   2   2   5   5   4    4  ...           0   
99996   1  2.0  4.0  3.0   1   1   1   5   5    5  ...           0   
99997   4  5.0  4.0  4.0   1   2   5   3   4    5  ...           0   
99998  12  7.5  6.0  6.0   4   4  10  10  10   10  ...           0   
99999   2  5.0  4.0  4.0   2   2   5   5   5    4  ...           0   

       City_İstanbul  City_İzmir  City_Şanlıurfa  City Group_Big Cities  \
0                  0           0               0                      0   
1                  0           0               0                      0   
2                  0           0               0                      1   
3                  0           0               0                      0   
4                  0           0               0                      0   
...              ...         ...             ...                    ...   
99995              0           0               0                      0   
99996              0           0               0                      0   
99997              1           0               0                      1   
99998              1           0               0                      1   
99999              1           0               0                      1   

       City Group_Other  Type_DT  Type_FC  Type_IL  Type_MB  
0                     1        0        1        0        0  
1                     1        0        0        1        0  
2                     0        0        1        0        0  
3                     1        0        0        1        0  
4                     1        0        1        0        0  
...                 ...      ...      ...      ...      ...  
99995                 1        0        1        0        0  
99996                 1        0        0        1        0  
99997                 0        0        0        1        0  
99998                 0        0        1        0        0  
99999                 0        0        0        1        0  

[100000 rows x 106 columns]

In [19]:
Y_Train

0      5653753.0
1      6923131.0
2      2055379.0
3      2675511.0
4      4316715.0
         ...    
132    5787594.0
133    9262754.0
134    2544857.0
135    7217634.0
136    6363241.0
Name: revenue, Length: 137, dtype: float64

In [54]:
X_train, X_test, Y_train, Y_test = train_test_split(Updated_Train_Data, Y_Train, test_size = .25)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(102, 106)
(35, 106)
(102,)
(35,)


In [55]:
#Decision Tree Regressor ========================================================================
#CONSTRUCT DEFAULT DECISION TREE AND OBTAIN RESPECTIVE ACCURACY 
dtr = DecisionTreeRegressor()
dtr.fit(X_train, Y_train)
dtr_predict_Train=dtr.predict(X_train)
mean_squared_error(Y_train,dtr_predict_Train)
print("RMSE (training) for Decision Tree:{0:10f}".format(mean_squared_error(Y_train,dtr_predict_Train)))
dtr_predict_Test=dtr.predict(X_test)
print("RMSE (test) for Decision Tree:{0:10f}".format(mean_squared_error(Y_test,dtr_predict_Test)))

RMSE (training) for Decision Tree:993343281309.416626
RMSE (test) for Decision Tree:10589351660808.292969


In [56]:
#CONSTRUCTING DECISION TREE - HYPERPARAMETER TUNING

import time
start_time = time.time()

dtr = DecisionTreeRegressor()
#X_train, X_test, Y_train, Y_test = train_test_split(Updated_Train_Data, Y_Train, test_size = .25,random_state=42)
parameters={'criterion':['squared_error', 'mse', 'absolute_error'],'min_weight_fraction_leaf':[0.01,0.05,0.1], 
            'splitter':['best', 'random'],'min_samples_leaf':[1,100,10]}
dtr_random = RandomizedSearchCV(dtr,parameters,n_iter=25,cv=5)
dtr_random.fit(X_train, Y_train)
grid_parm1=dtr_random.best_params_ 
print(grid_parm1)
dtrRand=DecisionTreeRegressor(**grid_parm1)
dtrRand.fit(X_train,Y_train)
dtrRand_predict=dtrRand.predict(X_test)
print("RMSE for Decision Tree:{0:10f}".format(mean_squared_error(Y_test,dtrRand_predict)))

#get cross-validation report
dtr_cv_score = cross_val_score(dtrRand, X_test, Y_test, cv=4)
print("=== All AUC Scores ===")
print(dtr_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Decision Tree: ",dtr_cv_score.mean())

print("--- %s seconds ---" % (time.time() - start_time))

{'splitter': 'best', 'min_weight_fraction_leaf': 0.1, 'min_samples_leaf': 100, 'criterion': 'mse'}
RMSE for Decision Tree:4781301709721.882812
=== All AUC Scores ===
[-0.0029041  -0.11779647 -0.09206608 -0.29744796]


=== Mean AUC Score ===
Mean AUC Score - Decision Tree:  -0.12755365210911324
--- 1.7453148365020752 seconds ---


In [58]:
X_Pred_test_dtr_Rand = dtrRand.predict(Updated_Test_Data)
X_Pred_test_dtr_Rand

array([4567248.26470588, 4567248.26470588, 4567248.26470588, ...,
       4567248.26470588, 4567248.26470588, 4567248.26470588])

In [60]:
result_test_dtr_random=pd.DataFrame(X_Test['Id'])
result_test_dtr_random['Prediction']=X_Pred_test_dtr_Rand
result_test_dtr_random.head()

Id    Prediction
0   0  4.567248e+06
1   1  4.567248e+06
2   2  4.567248e+06
3   3  4.567248e+06
4   4  4.567248e+06

In [25]:
result_test_dtr_random.isna().sum()

Id            0
Prediction    0
dtype: int64

In [ ]:
result_test_dtr_random.to_csv("/gdrive/My Drive/CS508/result_test_dtr_random.csv", index = None)

In [61]:
#Gradient Boosting Regressor================================================================================
#CONSTRUCT GRADIENT BOOSTING AND OBTAIN RESPECTIVE ACCURACY 
gbr = GradientBoostingRegressor()
gbr.fit(X_train, Y_train)
gbr_predict_Train=gbr.predict(X_train)
mean_squared_error(Y_train,gbr_predict_Train)
print("RMSE (training) for Decision Tree:{0:10f}".format(mean_squared_error(Y_train,gbr_predict_Train)))
gbr_predict_Test=gbr.predict(X_test)
print("RMSE (test) for Decision Tree:{0:10f}".format(mean_squared_error(Y_test,gbr_predict_Test)))



RMSE (training) for Decision Tree:1340413493187.457031
RMSE (test) for Decision Tree:10119832673252.728516


In [62]:
#CONSTRUCTING GRADIENT BOOSTING - HYPERPARAMETER TUNING
gbr = GradientBoostingRegressor()
parameters={'n_estimators':[5,10,20],'learning_rate':[0.01,.1]}
gbr_random = RandomizedSearchCV(gbr,parameters,n_iter=25,cv=5)
gbr_random.fit(X_train, Y_train)
grid_parm2=gbr_random.best_params_ 
print(grid_parm2)
gbrRand=GradientBoostingRegressor(**grid_parm2)
gbrRand.fit(X_train,Y_train)
gbrRand_predict=gbrRand.predict(X_test)
print("RMSE for Gradient Boosting:{0:10f}".format(mean_squared_error(Y_test,gbrRand_predict)))

#get cross-validation report
gbr_cv_score = cross_val_score(gbrRand, X_test, Y_test, cv=4)
print("=== All AUC Scores ===")
print(gbr_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Decision Tree: ",gbr_cv_score.mean())

{'n_estimators': 20, 'learning_rate': 0.01}
RMSE for Gradient Boosting:4824768489200.232422
=== All AUC Scores ===
[ 0.11195366 -0.09237863 -0.04813231 -0.4735624 ]


=== Mean AUC Score ===
Mean AUC Score - Decision Tree:  -0.12552992208010372


In [63]:
X_Pred_test_gbr_Rand = gbrRand.predict(Updated_Test_Data)
X_Pred_test_gbr_Rand

array([4367686.4939442 , 4367686.4939442 , 4367686.4939442 , ...,
       4589873.10261792, 4589873.10261792, 4589873.10261792])

In [64]:
result_test_gbr_random=pd.DataFrame(X_Test['Id'])
result_test_gbr_random['Prediction']=X_Pred_test_gbr_Rand
result_test_gbr_random.head()

Id    Prediction
0   0  4.367686e+06
1   1  4.367686e+06
2   2  4.367686e+06
3   3  4.367686e+06
4   4  4.367686e+06

In [ ]:
result_test_gbr_random.isna().sum()

Id            0
Prediction    0
dtype: int64

In [ ]:
result_test_gbr_random.to_csv("/gdrive/My Drive/CS508/result_test_gbr_random.csv", index = None)

In [65]:
#Random Forest Regressor ========================================================================
#CONSTRUCT DEFAULT Random Forest Regressor AND OBTAIN RESPECTIVE ACCURACY 
rfr = RandomForestRegressor()
rfr.fit(X_train, Y_train)
rfr_predict_Train=rfr.predict(X_train)
mean_squared_error(Y_train,rfr_predict_Train)
print("RMSE (training) for Random Forest:{0:10f}".format(mean_squared_error(Y_train,rfr_predict_Train)))
rfr_predict_Test=rfr.predict(X_test)
print("RMSE (test) for Random Forest:{0:10f}".format(mean_squared_error(Y_test,rfr_predict_Test)))

RMSE (training) for Random Forest:1698067110441.046631
RMSE (test) for Random Forest:6468002171150.518555


In [66]:
#CONSTRUCTING Random Forest - HYPERPARAMETER TUNING
rfr = RandomForestRegressor()
#X_train, X_test, Y_train, Y_test = train_test_split(Updated_Train_Data, Y_Train, test_size = .25,random_state=42)
parameters={'criterion':['squared_error', 'mse', 'absolute_error'],'min_weight_fraction_leaf':[0.01,0.05,0.1], 
            'n_estimators':[100],'min_samples_leaf':[1,100,10]}
rfr_random = RandomizedSearchCV(rfr,parameters,n_iter=25,cv=5)
rfr_random.fit(X_train, Y_train)
grid_parm1=rfr_random.best_params_ 
print(grid_parm1)
rfrRand=RandomForestRegressor(**grid_parm1)
rfrRand.fit(X_train,Y_train)
rfrRand_predict=rfrRand.predict(X_test)
print("RMSE for Random Forest:{0:10f}".format(mean_squared_error(Y_test,rfrRand_predict)))

#get cross-validation report
rfr_cv_score = cross_val_score(rfrRand, X_test, Y_test, cv=4)
print("=== All AUC Scores ===")
print(rfr_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - Random Forest: ",rfr_cv_score.mean())

{'n_estimators': 100, 'min_weight_fraction_leaf': 0.05, 'min_samples_leaf': 100, 'criterion': 'mse'}
RMSE for Random Forest:4736285891337.414062
=== All AUC Scores ===
[-0.00525044 -0.12148428 -0.08273911 -0.27199218]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  -0.12036650158546625


In [68]:
X_Pred_test_rfr_Rand = rfrRand.predict(Updated_Test_Data)
X_Pred_test_rfr_Rand

array([4513428.04372549, 4513428.04372549, 4513428.04372549, ...,
       4513428.04372549, 4513428.04372549, 4513428.04372549])

In [69]:
result_test_rfr_random=pd.DataFrame(X_Test['Id'])
result_test_rfr_random['Prediction']=X_Pred_test_rfr_Rand
result_test_rfr_random.head()

Id    Prediction
0   0  4.513428e+06
1   1  4.513428e+06
2   2  4.513428e+06
3   3  4.513428e+06
4   4  4.513428e+06

In [35]:
result_test_rfr_random.to_csv("/gdrive/My Drive/CS508/result_test_rfr_random.csv", index = None)

In [70]:
#MLP Regressor================================================================================
#CONSTRUCT MLP AND OBTAIN RESPECTIVE ACCURACY 
mlp = MLPRegressor()
mlp.fit(X_train, Y_train)
mlp_predict_Train=mlp.predict(X_train)
mean_squared_error(Y_train,mlp_predict_Train)
print("RMSE (training) for MLP Regressor:{0:10f}".format(mean_squared_error(Y_train,mlp_predict_Train)))
mlp_predict_Test=mlp.predict(X_test)
print("RMSE (test) for MLP Regressor:{0:10f}".format(mean_squared_error(Y_test,mlp_predict_Test)))

RMSE (training) for MLP Regressor:28079367251480.332031
RMSE (test) for MLP Regressor:21569451085515.433594


In [71]:
#CONSTRUCTING MLP REGRESSOR - HYPERPARAMETER TUNING
mlp = MLPRegressor()
parameters={'hidden_layer_sizes':[100],'activation':['relu','logistic'],'solver':['adam','lbfgs']}
mlp_random = RandomizedSearchCV(mlp,parameters,n_iter=25,cv=5)
mlp_random.fit(X_train, Y_train)
grid_parm2=mlp_random.best_params_ 
print(grid_parm2)
mlpRand=MLPRegressor(**grid_parm2)
mlpRand.fit(X_train,Y_train)
mlpRand_predict=mlpRand.predict(X_test)
print("RMSE for MLP Regressor:{0:10f}".format(mean_squared_error(Y_test,mlpRand_predict)))

#get cross-validation report
mlp_cv_score = cross_val_score(mlpRand, X_test, Y_test, cv=4)
print("=== All AUC Scores ===")
print(mlp_cv_score)
print('\n')
print("=== Mean AUC Score ===")
print("Mean AUC Score - MLP Regressor: ",mlp_cv_score.mean())

{'solver': 'lbfgs', 'hidden_layer_sizes': 100, 'activation': 'logistic'}
RMSE for MLP Regressor:4186591723453.450684
=== All AUC Scores ===
[-0.0029041  -0.01311835 -0.15979947 -0.29744798]


=== Mean AUC Score ===
Mean AUC Score - MLP Regressor:  -0.11831747533924847


In [72]:
X_Pred_test_MLP_Rand = mlpRand.predict(Updated_Test_Data)
X_Pred_test_MLP_Rand

array([5137046.01292829, 5137046.01292829, 5137046.01292829, ...,
       5291454.01014826, 5137046.01292829, 5137046.01292829])

In [73]:
result_test_MLP_random=pd.DataFrame(X_Test['Id'])
result_test_MLP_random['Prediction']=X_Pred_test_MLP_Rand
result_test_MLP_random.tail()

Id    Prediction
99995  99995  5.137046e+06
99996  99996  3.803724e+06
99997  99997  5.291454e+06
99998  99998  5.137046e+06
99999  99999  5.137046e+06

In [43]:
result_test_MLP_random.to_csv("/gdrive/My Drive/CS508/result_test_MLP_random.csv", index = None)

#models = [ DecisionTreeRegressor(), GradientBoostingRegressor(), RandomForestRegressor(), MLPRegressor() ]

#S_Train, S_Test = stacking(models,                   
                           Updated_Train_Data, Y_Train, Updated_Test_Data,   
                           regression=True, 

In [81]:
#STACKING MODELS =====================================================================
print("___________________________________________________________________________________________\nEnsemble Methods Predictions using GradientBoosting, RandomForest and Decision Tree Classifier\n")

models = [ DecisionTreeRegressor(), GradientBoostingRegressor(), RandomForestRegressor(), MLPRegressor() ]
      
S_Train, S_Test = stacking(models,                   
                           Updated_Train_Data, Y_Train, Updated_Test_Data,   
                           regression=True, 
     
                           mode='oof_pred_bag', 
       
                           needs_proba=False,
         
                           save_dir=None, 
                                        
                           n_folds=4,
                           
                           shuffle=True,
                                                    
                           verbose=2)



___________________________________________________________________________________________
Ensemble Methods Predictions using GradientBoosting, RandomForest and Decision Tree Classifier

task:         [regression]
metric:       [mean_absolute_error]
mode:         [oof_pred_bag]
n_models:     [4]

model  0:     [DecisionTreeRegressor]
    fold  0:  [1982696.05714286]
    fold  1:  [2342118.95588235]
    fold  2:  [3079409.76470588]
    fold  3:  [1933083.94117647]
    ----
    MEAN:     [2334327.17972689] + [458216.47533310]
    FULL:     [2331760.52919708]

model  1:     [GradientBoostingRegressor]
    fold  0:  [1616193.86488345]
    fold  1:  [1612596.03139909]
    fold  2:  [2638188.61065232]
    fold  3:  [2337941.08906639]
    ----
    MEAN:     [2051229.89900031] + [449549.73486819]
    FULL:     [2048054.45349581]

model  2:     [RandomForestRegressor]
    fold  0:  [1466303.91885714]
    fold  1:  [1318987.65866667]
    fold  2:  [2117906.20088235]
    fold  3:  [2076011.90012

In [85]:
#STACKING - CONTRUCT A GRADIENT BOOSTING MODEL==============================
import time
start_time = time.time()

gbr = GradientBoostingRegressor()

Gradient_parameters={'n_estimators':[5,10,20],'learning_rate':[0.01,.1]}

gbr_random = RandomizedSearchCV(gbc,Gradient_parameters,n_iter=10,cv=5)

gbr_random.fit(S_Train, Y_Train)

gbr_grid_parm=gbc_random.best_params_
print(gbr_grid_parm)
gbrRand=GradientBoostingRegressor(**gbr_grid_parm)
gbrRand.fit(S_Train, Y_Train)
gbrRand_predict=gbrRand.predict(S_Train)
#print('Final prediction score for ensemble methods: [%.8f]' % accuracy_score(gbcRand_predict, y_res1))

print("--- %s seconds ---" % (time.time() - start_time))


{'n_estimators': 5, 'learning_rate': 0.1}
--- 0.3679780960083008 seconds ---


In [87]:
X_Pred_test_gbr_Rand = gbrRand.predict(S_Test)
X_Pred_test_gbr_Rand

array([4731251.79078982, 4433607.90648229, 4178206.58355196, ...,
       4632407.70482611, 4632407.70482611, 4731407.66270992])

In [91]:
result_test_gbr_HLL=pd.DataFrame(X_Test['Id'])
result_test_gbr_HLL['Prediction']=X_Pred_test_gbr_Rand

result_test_gbr_HLL.to_csv(r'C:\Users\Arun Iyer\Google Drive\ASU Q1\Data Mining 1\Team Assignment 1\Results\result_test_gbr_HLL.csv', index = None)

In [92]:
result_test_gbr_HLL.head()

Id    Prediction
0   0  4.731252e+06
1   1  4.433608e+06
2   2  4.178207e+06
3   3  4.178207e+06
4   4  4.731252e+06

In [ ]:
#mean_squared_error(Y_Train,gbcRand_predict)
#print("RMSE (training) for Decision Tree:{0:10f}".format(mean_squared_error(Y_Train,gbcRand_predict)))
#mean_squared_error(y_test,y_pred_test)
#print("RMSE (Test Data) for Decision Tree:{0:10f}".format(mean_squared_error(y_test,y_pred_test)))

In [ ]:
#Save predictions
#df_stacking=pd.DataFrame()
#df_stacking['TARGET']=y_pred_test
#export_csv = df_rfc.to_csv(r'/gdrive/My Drive/Asim Roy/Datasets/Stacking_Test.csv')